# 개발용 컨테이너 및 컴포스 파일
# docker compose --env-file ./backend/.env.development -f ./container/compose.dev.yml up -d
services:
  postgres:
    image: postgres:17
    container_name: potato-land-db
    ports:
      - "127.0.0.1:${DATABASE_PORT}:5432"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

    healthcheck:
      test: [
        "CMD-SHELL",
        "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"
      ]
      interval: 5s
      timeout: 5s
      retries: 5
    
    volumes:
      - potato_land_postgres_data:/var/lib/postgresql/data
    
  redis:
    image: redis:7
    container_name: potato-land-redis
    
    command:
      - redis-server
      - --requirepass
      - ${REDIS_PASSWORD}
    
    environment:
      REDISCLI_AUTH: ${REDIS_PASSWORD}

    ports:
      - "127.0.0.1:${REDIS_PORT}:6379"

    healthcheck:
      test: [
        "CMD",
        "redis-cli", "ping"
      ]
      interval: 5s
      timeout: 5s
      retries: 5

    volumes:
      - potato_land_redis_data:/data

volumes:
  potato_land_postgres_data:
  potato_land_redis_data:
