CREATE TYPE user_role AS ENUM (
  'USER',
  'ADMIN'
);

CREATE TYPE notification_type AS ENUM (
  'NEW_CHAT_ROOM',
  'NEW_MESSAGE',
  'NEW_BID',
  'OUTBID',
  'AUCTION_WON',
  'AUCTION_ENDED',
  'AUCTION_ENDED_WITHOUT_BID',
  'AUCTION_LEADER_CHANGED',
  'LISTING_DELETED',
  'PAYMENT_REQUESTED',
  'PAYMENT_RECEIVED',
  'PAYMENT_CANCELED',
  'NEW_REVIEW'
);

CREATE TYPE notification_reference_type AS ENUM (
  'CHAT_ROOM',
  'CHAT_MESSAGE',
  'LISTING',
  'TRANSACTION',
  'REVIEW',
  'AUCTION'
);

CREATE TYPE listing_type AS ENUM (
  'USED',
  'AUCTION'
);

CREATE TYPE product_status AS ENUM (
  'NEW',
  'LIKE_NEW',
  'USED',
  'DAMAGED'
);

CREATE TYPE used_trade_status AS ENUM (
  'ON_SALE',
  'SOLD'
);

CREATE TYPE auction_status AS ENUM (
  'ON_GOING',
  'FINISHED'
);

CREATE TYPE chat_message_type AS ENUM (
  'TEXT',
  'IMAGE',
  'SYSTEM',
  'PAYMENT_REQUEST',
  'TRADE_COMPLETE'
);

CREATE TYPE transaction_type AS ENUM (
  'DIRECT_SALE',
  'AUCTION'
);

CREATE TYPE transaction_status AS ENUM (
  'REQUESTED',
  'COMPLETED',
  'CANCELED'
);

CREATE TABLE users (
  idx BIGINT GENERATED BY DEFAULT AS IDENTITY,
  login_id VARCHAR(50) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  name VARCHAR(50) NOT NULL,
  nickname VARCHAR(50) NOT NULL,
  phone VARCHAR(30) NOT NULL,
  email VARCHAR(255),
  profile_image VARCHAR(2048),
  bio VARCHAR(255),
  role user_role NOT NULL DEFAULT 'USER',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMPTZ,
  banned_at TIMESTAMPTZ,
  banned_until TIMESTAMPTZ,
  ban_reason TEXT,
  admin_memo TEXT,

  CONSTRAINT pk_users PRIMARY KEY (idx),
  CONSTRAINT uq_users_login_id UNIQUE (login_id),
  CONSTRAINT uq_users_nickname UNIQUE (nickname),
  CONSTRAINT uq_users_phone UNIQUE (phone),
  CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE TABLE categories (
  idx BIGINT GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(100) NOT NULL,
  sort_order INTEGER NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,

  CONSTRAINT pk_categories PRIMARY KEY (idx),
  CONSTRAINT uq_categories_name UNIQUE (name),
  CONSTRAINT chk_categories_sort_order CHECK (sort_order > 0)
);

CREATE INDEX idx_categories_sort_order
  ON categories (sort_order);

CREATE TABLE notifications (
  idx BIGINT GENERATED BY DEFAULT AS IDENTITY,
  receiver_idx BIGINT NOT NULL,
  notification_type notification_type NOT NULL,
  reference_type notification_reference_type NOT NULL,
  reference_idx BIGINT NOT NULL,
  content TEXT NOT NULL,
  is_read BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT pk_notifications PRIMARY KEY (idx),
  CONSTRAINT fk_notifications_receiver
    FOREIGN KEY (receiver_idx) REFERENCES users (idx)
);

CREATE INDEX idx_notifications_receiver_read_created
  ON notifications (receiver_idx, is_read, created_at DESC);

CREATE TABLE listings (
  idx BIGINT GENERATED BY DEFAULT AS IDENTITY,
  seller_idx BIGINT NOT NULL,
  category_idx BIGINT NOT NULL,
  listing_type listing_type NOT NULL,
  title VARCHAR(200) NOT NULL,
  description TEXT NOT NULL,
  preferred_trade_location VARCHAR(255),
  product_status product_status NOT NULL,
  view_count BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMPTZ,
  deleted_by BIGINT,
  delete_reason TEXT,

  CONSTRAINT pk_listings PRIMARY KEY (idx),
  CONSTRAINT fk_listings_seller
    FOREIGN KEY (seller_idx) REFERENCES users (idx),
  CONSTRAINT fk_listings_category
    FOREIGN KEY (category_idx) REFERENCES categories (idx),
  CONSTRAINT fk_listings_deleted_by
    FOREIGN KEY (deleted_by) REFERENCES users (idx),
  CONSTRAINT chk_listings_view_count CHECK (view_count >= 0)
);

CREATE INDEX idx_listings_seller
  ON listings (seller_idx);

CREATE INDEX idx_listings_category
  ON listings (category_idx);

CREATE INDEX idx_listings_type_created
  ON listings (listing_type, created_at DESC);

CREATE INDEX idx_listings_deleted_type_created
  ON listings (deleted_at, listing_type, created_at DESC);

CREATE TABLE favorites (
  user_idx BIGINT NOT NULL,
  listing_idx BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT pk_favorites PRIMARY KEY (user_idx, listing_idx),
  CONSTRAINT fk_favorites_user
    FOREIGN KEY (user_idx) REFERENCES users (idx),
  CONSTRAINT fk_favorites_listing
    FOREIGN KEY (listing_idx) REFERENCES listings (idx)
);

CREATE INDEX idx_favorites_listing
  ON favorites (listing_idx);

CREATE TABLE used_posts (
  listing_idx BIGINT,
  price BIGINT NOT NULL,
  trade_status used_trade_status NOT NULL DEFAULT 'ON_SALE',

  CONSTRAINT pk_used_posts PRIMARY KEY (listing_idx),
  CONSTRAINT fk_used_posts_listing
    FOREIGN KEY (listing_idx) REFERENCES listings (idx),
  CONSTRAINT chk_used_posts_price CHECK (price >= 0)
);

CREATE TABLE auction_posts (
  listing_idx BIGINT,
  start_price BIGINT NOT NULL,
  current_price BIGINT NOT NULL,
  bid_unit BIGINT NOT NULL,
  started_at TIMESTAMPTZ NOT NULL,
  ends_at TIMESTAMPTZ NOT NULL,
  status auction_status NOT NULL DEFAULT 'ON_GOING',
  winning_bid_idx BIGINT,

  CONSTRAINT pk_auction_posts PRIMARY KEY (listing_idx),
  CONSTRAINT fk_auction_posts_listing
    FOREIGN KEY (listing_idx) REFERENCES listings (idx),
  CONSTRAINT chk_auction_posts_start_price CHECK (start_price >= 0),
  CONSTRAINT chk_auction_posts_current_price
    CHECK (current_price >= start_price),
  CONSTRAINT chk_auction_posts_bid_unit CHECK (bid_unit >= 100),
  CONSTRAINT chk_auction_posts_period CHECK (ends_at > started_at)
);

CREATE TABLE auction_bids (
  idx BIGINT GENERATED BY DEFAULT AS IDENTITY,
  listing_idx BIGINT NOT NULL,
  bidder_idx BIGINT NOT NULL,
  bid_price BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT pk_auction_bids PRIMARY KEY (idx),
  CONSTRAINT fk_auction_bids_listing
    FOREIGN KEY (listing_idx) REFERENCES auction_posts (listing_idx),
  CONSTRAINT fk_auction_bids_bidder
    FOREIGN KEY (bidder_idx) REFERENCES users (idx),
  CONSTRAINT chk_auction_bids_price CHECK (bid_price >= 0)
);

CREATE INDEX idx_auction_bids_listing_price
  ON auction_bids (listing_idx, bid_price DESC);

ALTER TABLE auction_posts
  ADD CONSTRAINT fk_auction_posts_winning_bid
  FOREIGN KEY (winning_bid_idx) REFERENCES auction_bids (idx);

CREATE TABLE post_images (
  idx BIGINT GENERATED BY DEFAULT AS IDENTITY,
  listing_idx BIGINT NOT NULL,
  image_url VARCHAR(2048) NOT NULL,
  sort_order INTEGER NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT pk_post_images PRIMARY KEY (idx),
  CONSTRAINT fk_post_images_listing
    FOREIGN KEY (listing_idx) REFERENCES listings (idx),
  CONSTRAINT uq_post_images_listing_order
    UNIQUE (listing_idx, sort_order),
  CONSTRAINT chk_post_images_sort_order CHECK (sort_order >= 0)
);

CREATE TABLE chat_rooms (
  idx BIGINT GENERATED BY DEFAULT AS IDENTITY,
  listing_idx BIGINT NOT NULL,
  buyer_idx BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_message_at TIMESTAMPTZ,

  CONSTRAINT pk_chat_rooms PRIMARY KEY (idx),
  CONSTRAINT fk_chat_rooms_listing
    FOREIGN KEY (listing_idx) REFERENCES listings (idx),
  CONSTRAINT fk_chat_rooms_buyer
    FOREIGN KEY (buyer_idx) REFERENCES users (idx),
  CONSTRAINT uq_chat_rooms_listing_buyer UNIQUE (listing_idx, buyer_idx)
);

CREATE INDEX idx_chat_rooms_buyer_recent
  ON chat_rooms (buyer_idx, last_message_at DESC);

CREATE TABLE transactions (
  idx BIGINT GENERATED BY DEFAULT AS IDENTITY,
  listing_idx BIGINT NOT NULL,
  seller_idx BIGINT NOT NULL,
  buyer_idx BIGINT NOT NULL,
  transaction_type transaction_type NOT NULL,
  status transaction_status NOT NULL DEFAULT 'REQUESTED',
  amount BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  completed_at TIMESTAMPTZ,
  canceled_by BIGINT,

  CONSTRAINT pk_transactions PRIMARY KEY (idx),
  CONSTRAINT fk_transactions_listing
    FOREIGN KEY (listing_idx) REFERENCES listings (idx),
  CONSTRAINT fk_transactions_seller
    FOREIGN KEY (seller_idx) REFERENCES users (idx),
  CONSTRAINT fk_transactions_buyer
    FOREIGN KEY (buyer_idx) REFERENCES users (idx),
  CONSTRAINT fk_transactions_canceled_by
    FOREIGN KEY (canceled_by) REFERENCES users (idx),
  CONSTRAINT chk_transactions_amount CHECK (amount >= 0),
  CONSTRAINT chk_transactions_participants CHECK (seller_idx <> buyer_idx)
);

CREATE INDEX idx_transactions_listing
  ON transactions (listing_idx);

CREATE INDEX idx_transactions_buyer
  ON transactions (buyer_idx);

CREATE INDEX idx_transactions_seller
  ON transactions (seller_idx);

CREATE UNIQUE INDEX uq_transactions_listing_active_or_completed
  ON transactions (listing_idx)
  WHERE status IN ('REQUESTED', 'COMPLETED');

CREATE TABLE chat_messages (
  idx BIGINT GENERATED BY DEFAULT AS IDENTITY,
  chat_room_idx BIGINT NOT NULL,
  sender_idx BIGINT,
  client_message_id VARCHAR(100),
  message_type chat_message_type NOT NULL,
  transaction_idx BIGINT,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT pk_chat_messages PRIMARY KEY (idx),
  CONSTRAINT fk_chat_messages_room
    FOREIGN KEY (chat_room_idx) REFERENCES chat_rooms (idx),
  CONSTRAINT fk_chat_messages_sender
    FOREIGN KEY (sender_idx) REFERENCES users (idx),
  CONSTRAINT fk_chat_messages_transaction
    FOREIGN KEY (transaction_idx) REFERENCES transactions (idx),
  CONSTRAINT uq_chat_messages_client_message
    UNIQUE (chat_room_idx, sender_idx, client_message_id),
  CONSTRAINT chk_chat_messages_sender_by_type CHECK (
    (message_type IN ('SYSTEM', 'TRADE_COMPLETE') AND sender_idx IS NULL)
    OR
    (message_type IN ('TEXT', 'IMAGE', 'PAYMENT_REQUEST') AND sender_idx IS NOT NULL)
  ),
  CONSTRAINT chk_chat_messages_client_message_id CHECK (
    message_type <> 'TEXT' OR client_message_id IS NOT NULL
  )
);

CREATE INDEX idx_chat_messages_room_recent
  ON chat_messages (chat_room_idx, created_at DESC, idx DESC);

CREATE TABLE reviews (
  idx BIGINT GENERATED BY DEFAULT AS IDENTITY,
  transaction_idx BIGINT NOT NULL,
  reviewer_idx BIGINT NOT NULL,
  reviewee_idx BIGINT NOT NULL,
  rating SMALLINT NOT NULL,
  content TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT pk_reviews PRIMARY KEY (idx),
  CONSTRAINT fk_reviews_transaction
    FOREIGN KEY (transaction_idx) REFERENCES transactions (idx),
  CONSTRAINT fk_reviews_reviewer
    FOREIGN KEY (reviewer_idx) REFERENCES users (idx),
  CONSTRAINT fk_reviews_reviewee
    FOREIGN KEY (reviewee_idx) REFERENCES users (idx),
  CONSTRAINT uq_reviews_transaction_reviewer
    UNIQUE (transaction_idx, reviewer_idx),
  CONSTRAINT chk_reviews_rating CHECK (rating BETWEEN 1 AND 10),
  CONSTRAINT chk_reviews_content_length
    CHECK (content IS NULL OR CHAR_LENGTH(content) <= 50),
  CONSTRAINT chk_reviews_participants CHECK (reviewer_idx <> reviewee_idx)
);

CREATE INDEX idx_reviews_reviewee
  ON reviews (reviewee_idx);
