DO $$ BEGIN
  CREATE TYPE review_tag_sentiment AS ENUM ('STRENGTH', 'WEAKNESS');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS review_tags (
  idx BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label VARCHAR(50) NOT NULL UNIQUE,
  sentiment review_tag_sentiment NOT NULL,
  sort_order INTEGER NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT chk_review_tags_sort_order CHECK (sort_order > 0)
);

CREATE TABLE IF NOT EXISTS review_tag_links (
  review_idx BIGINT NOT NULL REFERENCES reviews (idx) ON DELETE CASCADE,
  tag_idx BIGINT NOT NULL REFERENCES review_tags (idx),
  PRIMARY KEY (review_idx, tag_idx)
);

CREATE INDEX IF NOT EXISTS idx_review_tags_active_order
  ON review_tags (is_active, sentiment, sort_order);
